### ISSUE TITLE
Ability to add tables to Quill Editor

### ISSUE THREAD

**Issue by deshetti** [factly/dega-gateway#112]
We need ability to add tables to Quill editor. The default editor does not have an option to do so. Here is the discussion on the topic on their github issues: https://github.com/quilljs/quill/issues/117

Support for tables is slated to be for release v2.0 and it doesn't look like there is much work done completed in that regard: https://github.com/quilljs/quill/projects/1

I see that there a plugin which seems to at least give us some support for tables in the mean time. Here is the plugin: https://www.npmjs.com/package/quill-table 

The github repo for the above plugin is: https://github.com/MrMadClown/quill-table
The above repo is forked and is ahead of a bunch of commits from: https://github.com/dost/quilljs-table
Here is the demo of the above repo which looks good to start with: http://quilljstable.timepress.cz/quilljs-extended-toolbar/index.html#

**Comment by soccerloway** [comment]
@deshetti  I make a quilljs module to add surpport for table named [quill-better-table](https://github.com/soccerloway/quill-better-table#readme), but requires quilljs v2.0.0-dev.3.
I hope that  quill-better-table could help you.
