### ISSUE TITLE
Clicking Publish when editing a factcheck is throwing an error

### ISSUE THREAD

**Issue by deshetti** [factly/dega-gateway#163]
When clicking publish after we edit a factcheck, following error is thrown: ```A new Factcheck cannot already have an ID```

**Comment by arghyaiitb** [comment]
I have update the frontend part and fixed the issue for now. But I feel the backend api can be improved unless there is some major constraint. There are 3 different api, which I would recommend to merge into 2. 

Currently 

- publish doesn’t work if the entry is present, but works only for new entry

- create can add new entry but cannot publish new entry

- update does what is should, irrespective of the state it would perform its task

Suggested. 

Remove publish and have only create and update. If a user created entry with publish or draft state then handle it as per the status flag. Update api doesn't need any change.

**Comment by deshetti** [comment]
@oddiraju  aren't we always supposed to call update once it is published for the first time for further edits?

Functionally we should support the following when a user edits a factcheck/post:

- Should be able to Update (This is in the case of already published factcheck/post). The status remains Publish. Right now clicking on Publish just calls the same api as it does when we create a new factcheck/post for the first time.
- Should be able to Save as Draft by clicking on Save Draft button (This changes the status from Publish to Draft).
