### ISSUE TITLE
Creating a Tag is throwing an error: 'A new Tag cannot already have an ID'

### ISSUE THREAD

**Issue by deshetti** [factly/dega-gateway#211]

**Comment by prasoonk587** [comment]
I am getting below response from the backend corresponding to the payload.
**Payload**
{
    "id": "",
    "name": "Test900",
    "slug": "",
    "description": "test",
    "clientId": "",
    "createdDate": null,
    "lastUpdatedDate": null
}
**Response**
{
    "entityName": "coreTag",
    "errorKey": "idexists",
    "type": "https://www.jhipster.tech/problem/problem-with-message",
    "title": "A new tag cannot already have an ID",
    "status": 400,
    "message": "error.idexists",
    "params": "coreTag"
}
I am getting same error for every request. @deshetti can you check with backend team.

**Comment by prasoonk587** [comment]
The issue has been fixed. we have deleted id key from the payload, now getting the correct response and tag are being generated
