### ISSUE TITLE
can't start keycloak.yml

### ISSUE THREAD

**Issue by korrio** [factly/dega-gateway#324]
https://github.com/factly/dega-gateway/blob/develop/src/main/docker/keycloak.yml

**Comment by deshetti** [comment]
Hi @korrio,

Not sure what you mean by can't start keycloak.yml? How are you starting it? Currently, there are a bunch of steps that need to be done manually to run the application end-end. We are in the process of making a major overhaul and rewriting the tool in Golang. 

Let us know what you are trying to do and how you plan to use dega?

Thanks,
Shashi

**Comment by korrio** [comment]
Good news! 
So I will wait for the Golang. Thanks!
